--[[ Protected by Lua Guard ]]

local Players = game:GetService("Players") local RunService = game:GetService("RunService") local _llIlIIIlll = game:GetService("UserInputService") local _IIIIIlIIlI = Players.LocalPlayer local _lIllIIlIlI = "https://discord.gg/QaAa3qBdSX" local _lIIIllIlll = Enum.KeyCode.LeftControl local _IIIlIlIIII = false local _IllllIllII = 0x46 local _lIlIIllllI = 0x10 local _llIllllIIl = false local _llIlIlIllI = false local _llIlllllIl = false local _IlIlIlIIll local _lIIIlIllll local _IlIlIIIIlI = {W=false,A=false,S=false,D=false,Space=false,Ctrl=false} local _IIIlIIllll = Color3.fromRGB(0x19,0x19,0x19) local _llIlIIIIll = Color3.fromRGB(0x0,0x0,0x0) local _lIlIIIIIlI = Color3.fromRGB(0x28,0x28,0x37) local _IlIllllllI = Color3.fromRGB(0x41,0x41,0x5F) local function _lIllIIllII(obj) obj.TextStrokeTransparency = 0x0 obj.TextStrokeColor3 = Color3.new(0x0,0x0,0x0) end
 local function _IIlIIlllIl(_llllllllII,x,_IIlIlIIIll,parent) local _lIlllIIIll = Instance.new("TextButton") _lIlllIIIll.Size = UDim2.new(0x0,0xB4,0x0,0x23) _lIlllIIIll.Position = UDim2.new(0x0,x,0x0,_IIlIlIIIll) _lIlllIIIll.Text = _llllllllII _lIlllIIIll.BackgroundColor3 = _lIlIIIIIlI _lIlllIIIll.TextColor3 = Color3.new(0x1,0x1,0x1) _lIlllIIIll.TextStrokeTransparency = 0x0 _lIlllIIIll.TextStrokeColor3 = Color3.new(0x0,0x0,0x0) _lIlllIIIll.Parent = parent local _IIIIIIllII = Instance.new("UICorner") _IIIIIIllII.CornerRadius = UDim.new(0x0,0x8) _IIIIIIllII.Parent = _lIlllIIIll _lIlllIIIll.MouseEnter:Connect( function () TweenService:Create(_lIlllIIIll,TweenInfo.new(0.15),{ BackgroundColor3 = _IlIllllllI }):Play() end
 ) _lIlllIIIll.MouseLeave:Connect( function () TweenService:Create(_lIlllIIIll,TweenInfo.new(0.15),{ BackgroundColor3 = _lIlIIIIIlI }):Play() end
 ) return _lIlllIIIll end
 local _IIIIlIIlIl = Instance.new("ScreenGui") _IIIIlIIlIl.Name = "BLACK FLAG" _IIIIlIIlIl.Parent = game.CoreGui if game.Lighting:FindFirstChildOfClass("BlurEffect") then game.Lighting:FindFirstChildOfClass("BlurEffect"):Destroy() end
 local _lllllIIllI = Instance.new("BlurEffect") _lllllIIllI.Size = 0x0 _lllllIIllI.Parent = game.Lighting local _lIlIlIIIlI = Instance.new("Frame") _lIlIlIIIlI.Size = UDim2.new(0x0,0x1B8,0x0,0x154) _lIlIlIIIlI.Position = UDim2.new(0.5,-0xDC,0.5,-0xAA) _lIlIlIIIlI.BackgroundColor3 = _IIIlIIllll _lIlIlIIIlI.Active = true _lIlIlIIIlI.Draggable = true _lIlIlIIIlI.Parent = _IIIIlIIlIl local TweenService = game:GetService("TweenService") local _lllIllIllI = "1234" _lIlIlIIIlI.Position = UDim2.new(-0x1,-0x1B8,0.5,-0xAA) local _lIIIIlIlIl = Instance.new("Frame") _lIIIIlIlIl.Size = UDim2.new(0x0,0x140,0x0,0xDC) _lIIIIlIlIl.Position = UDim2.new(0.5,-0xA0,0.5,-0x6E) _lIIIIlIlIl.BackgroundColor3 = _IIIlIIllll _lIIIIlIlIl.Parent = _IIIIlIIlIl local _lIllllIIlI = Instance.new("TextLabel") _lIllllIIlI.Size = UDim2.new(0x1,0x0,0x0,0x28) _lIllllIIlI.Text = "BLACK FLAG Key System" _lIllllIIlI.TextScaled = true _lIllllIIlI.BackgroundTransparency = 0x1 _lIllllIIlI.TextColor3 = Color3.new(0x1,0x1,0x1) _lIllllIIlI.Parent = _lIIIIlIlIl _lIllIIllII(_lIllllIIlI) RunService.RenderStepped:Connect( function () local _IIIIIIllll = (tick() % 0x5) / 0x5 local _IIIlIIllII = Color3.fromHSV(_IIIIIIllll,0x1,0x1) if _lIllllIIlI then _lIllllIIlI.TextColor3 = _IIIlIIllII end
 end
 ) local _IlllIIIlll = Instance.new("TextLabel") _IlllIIIlll.Size = UDim2.new(0x1,-0x14,0x0,0x1E) _IlllIIIlll.Position = UDim2.new(0x0,0xA,0x0,0x23) _IlllIIIlll.Text = "Get the key from our Discord server" _IlllIIIlll.TextScaled = true _IlllIIIlll.BackgroundTransparency = 0x1 _IlllIIIlll.TextColor3 = Color3.fromRGB(0xC8,0xC8,0xC8) _IlllIIIlll.Parent = _lIIIIlIlIl _lIllIIllII(_IlllIIIlll) local _lllIllIlIl = Instance.new("TextButton") _lllIllIlIl.Size = UDim2.new(0x0,0xC8,0x0,0x23) _lllIllIlIl.Position = UDim2.new(0.5,-0x64,0x0,0x46) _lllIllIlIl.Text = " Copy Discord Invite" _lllIllIlIl.BackgroundColor3 = _llIlIIIIll _lllIllIlIl.TextColor3 = Color3.new(0x1,0x1,0x1) _lllIllIlIl.TextScaled = true _lllIllIlIl.Parent = _lIIIIlIlIl _lIllIIllII(_lllIllIlIl) local _lIIlIllllI = Instance.new("ImageLabel") _lIIlIllllI.Size = UDim2.new(0x0,0x16,0x0,0x16) _lIIlIllllI.Position = UDim2.new(0x0,0x6,0.5,-0xB) _lIIlIllllI.BackgroundTransparency = 0x1 _lIIlIllllI.Parent = _lllIllIlIl _lllIllIlIl.MouseButton1Click:Connect( function () if setclipboard then setclipboard(_lIllIIlIlI) end
 end
 ) local _IIlIlIlIIl = Instance.new("TextBox") _IIlIlIlIIl.Size = UDim2.new(0.8,0x0,0x0,0x23) _IIlIlIlIIl.Position = UDim2.new(0.1,0x0,0x0,0x73) _IIlIlIlIIl.PlaceholderText = "Enter Key..." _IIlIlIlIIl.Text = "" _IIlIlIlIIl.TextScaled = true _IIlIlIlIIl.BackgroundColor3 = _lIlIIIIIlI _IIlIlIlIIl.TextColor3 = Color3.new(0x1,0x1,0x1) _IIlIlIlIIl.Parent = _lIIIIlIlIl _lIllIIllII(_IIlIlIlIIl) local _llIIIIIlll = Instance.new("TextButton") _llIIIIIlll.Size = UDim2.new(0.6,0x0,0x0,0x23) _llIIIIIlll.Position = UDim2.new(0.2,0x0,0x0,0xA0) _llIIIIIlll.Text = "Submit" _llIIIIIlll.TextScaled = true _llIIIIIlll.BackgroundColor3 = _llIlIIIIll _llIIIIIlll.TextColor3 = Color3.new(0x1,0x1,0x1) _llIIIIIlll.Parent = _lIIIIlIlIl _lIllIIllII(_llIIIIIlll) local _IlIlIIIlIl = Instance.new("TextLabel") _IlIlIIIlIl.Size = UDim2.new(0x1,0x0,0x0,0x14) _IlIlIIIlIl.Position = UDim2.new(0x0,0x0,0x1,-0x14) _IlIlIIIlIl.BackgroundTransparency = 0x1 _IlIlIIIlIl.TextColor3 = Color3.fromRGB(0xFF,0x50,0x50) _IlIlIIIlIl.TextScaled = true _IlIlIIIlIl.Text = "" _IlIlIIIlIl.Parent = _lIIIIlIlIl _lIllIIllII(_IlIlIIIlIl) _llIIIIIlll.MouseButton1Click:Connect( function () if _IIlIlIlIIl.Text == _lllIllIllI then for _,v in pairs(_lIIIIlIlIl:GetChildren()) do if v:IsA("TextLabel") or v:IsA("TextButton") or v:IsA("TextBox") then TweenService:Create(v,TweenInfo.new(0.35),{ TextTransparency = 0x1, BackgroundTransparency = 0x1 }):Play() end
 end
 TweenService:Create(_lIIIIlIlIl,TweenInfo.new(0.35),{ BackgroundTransparency = 0x1 }):Play() task.wait(0.35) _lIIIIlIlIl:Destroy() local _IllllIIIIl = TweenService:Create( _lIlIlIIIlI, TweenInfo.new(0.4,Enum.EasingStyle.Quad,Enum.EasingDirection.Out), {Position = UDim2.new(0.5,-0xDC,0.5,-0xAA)} ) _IllllIIIIl:Play() TweenService:Create(_lllllIIllI, TweenInfo.new(0.3), {Size = 0xE}):Play() else _IlIlIIIlIl.Text = "Invalid Key" end
 end
 ) local _llllIllIll = Instance.new("Frame") _llllIllIll.Size = UDim2.new(0x1,0x0,0x0,0x23) _llllIllIll.BackgroundColor3 = _llIlIIIIll _llllIllIll.Parent = _lIlIlIIIlI local _llllIlIIlI = Instance.new("UICorner") _llllIlIIlI.CornerRadius = UDim.new(0x0,0xC) _llllIlIIlI.Parent = _llllIllIll local _llIIIIlIlI = Instance.new("Frame") _llIIIIlIlI.Size = UDim2.new(0x0,0xC8,0x1,0x0) _llIIIIlIlI.Position = UDim2.new(0x0,0xA,0x0,0x0) _llIIIIlIlI.BackgroundTransparency = 0x1 _llIIIIlIlI.Parent = _llllIllIll local _IIlIlIllIl = Instance.new("UICorner") _IIlIlIllIl.CornerRadius = UDim.new(0x0,0xC) _IIlIlIllIl.Parent = _llIIIIlIlI local _IlIIIIIIIl = Instance.new("TextLabel") _IlIIIIIIIl.Size = UDim2.new(0x0,0x50,0.8,0x0) _IlIIIIIIIl.Position = UDim2.new(0x0,0x0,0.1,0x0) _IlIIIIIIIl.Text = "BLACK" _IlIIIIIIIl.TextScaled = true _IlIIIIIIIl.TextColor3 = Color3.new(0x0,0x0,0x0) _IlIIIIIIIl.BackgroundColor3 = Color3.new(0x1,0x1,0x1) _IlIIIIIIIl.BorderSizePixel = 0x0 _IlIIIIIIIl.Parent = _llIIIIlIlI local _lIlIlIIIlI = Instance.new("UICorner") _lIlIlIIIlI.CornerRadius = UDim.new(0x0,0x7) _lIlIlIIIlI.Parent = _IlIIIIIIIl local _IllIIIllIl = Instance.new("TextLabel") _IllIIIllIl.Size = UDim2.new(0x0,0x46,0.8,0x0) _IllIIIllIl.Position = UDim2.new(0x0,0x55,0.1,0x0) _IllIIIllIl.Text = "FLAG" _IllIIIllIl.TextScaled = true _IllIIIllIl.TextColor3 = Color3.new(0x1,0x1,0x1) _IllIIIllIl.BackgroundColor3 = Color3.new(0x0,0x0,0x0) _IllIIIllIl.BorderSizePixel = 0x0 _IllIIIllIl.Parent = _llIIIIlIlI local _IIIlIIIIlI = Instance.new("TextButton") _IIIlIIIIlI.Size = UDim2.new(0x0,0x23,0x1,0x0) _IIIlIIIIlI.Position = UDim2.new(0x1,-0x23,0x0,0x0) _IIIlIIIIlI.Text = "X" _IIIlIIIIlI.BackgroundColor3 = Color3.fromRGB(0x3E8,0x3E8,0x3E8) _IIIlIIIIlI.TextColor3 = Color3.new(0x1,0x1,0x1) _IIIlIIIIlI.Parent = _llllIllIll _lIllIIllII(_IIIlIIIIlI) local _IllIIlllII = Instance.new("UICorner") _IllIIlllII.CornerRadius = UDim.new(0x0,0xC) _IllIIlllII.Parent = _IIIlIIIIlI _IIIlIIIIlI.MouseButton1Click:Connect( function () if _lllllIIllI and _lllllIIllI.Parent then _lllllIIllI:Destroy() end
 _IIIIlIIlIl:Destroy() end
 ) local _lllIIIlIll = Instance.new("Frame") _lllIIIlIll.Size = UDim2.new(0x1,0x0,0x0,0x1E) _lllIIIlIll.Position = UDim2.new(0x0,0x0,0x0,0x23) _lllIIIlIll.BackgroundColor3 = Color3.fromRGB(0x14,0x14,0x1E) _lllIIIlIll.Parent = _lIlIlIIIlI local _llIIIIlIII = Instance.new("UICorner") _llIIIIlIII.CornerRadius = UDim.new(0x0,0xC) _llIIIIlIII.Parent = _lllIIIlIll local function _lIllIlIIlI(name,pos) local _lIlllIIIll = Instance.new("TextButton") _lIlllIIIll.Size = UDim2.new(0.2,0x0,0x1,0x0) _lIlllIIIll.Position = pos _lIlllIIIll.Text = name _lIlllIIIll.BackgroundColor3 = _lIlIIIIIlI _lIlllIIIll.TextColor3 = Color3.new(0x1,0x1,0x1) _lIlllIIIll.Parent = _lllIIIlIll _lIllIIllII(_lIlllIIIll) _lIlllIIIll.MouseEnter:Connect( function () _lIlllIIIll.BackgroundColor3 = _IlIllllllI end
 ) _lIlllIIIll.MouseLeave:Connect( function () _lIlllIIIll.BackgroundColor3 = _lIlIIIIIlI end
 ) return _lIlllIIIll end
 local _IIlllIIIlI = _lIllIlIIlI("Main", UDim2.new(0x0, 0x0, 0x0, 0x0)) local _IIIIIlIlIl = _lIllIlIIlI("Player", UDim2.new(0.2, 0x0, 0x0, 0x0)) local _llIlIlIlll = _lIllIlIIlI("View", UDim2.new(0.4, 0x0, 0x0, 0x0)) local _lllIIIlIIl = _lIllIlIIlI("Server", UDim2.new(0.6, 0x0, 0x0, 0x0)) local _lIIIllIIIl = _lIllIlIIlI("Settings", UDim2.new(0.8, 0x0, 0x0, 0x0)) print(_IIlllIIIlI, _IIIIIlIlIl, _llIlIlIlll, _lllIIIlIIl, _lIIIllIIIl) local _lIIlIIllIl = Instance.new("Frame") _lIIlIIllIl.Size = UDim2.new(0x1,0x0,0x1,-0x41) _lIIlIIllIl.Position = UDim2.new(0x0,0x0,0x0,0x41) _lIIlIIllIl.BackgroundTransparency = 0x1 _lIIlIIllIl.Parent = _lIlIlIIIlI local _IIllIlllll = Instance.new("UICorner") _IIllIlllll.CornerRadius = UDim.new(0x0,0xC) _IIllIlllll.Parent = _lIIlIIllIl local _lIIIIIllIl = Instance.new("Frame") _lIIIIIllIl.Size = UDim2.new(0x1,0x0,0x1,0x0) _lIIIIIllIl.BackgroundTransparency = 0x1 _lIIIIIllIl.Parent = _lIIlIIllIl local _IIIlIIIIll = Instance.new("UIStroke") _IIIlIIIIll.Color = Color3.fromRGB(0x0,0x0,0x0) _IIIlIIIIll.Thickness = 0x4 _IIIlIIIIll.Parent = _lIlIlIIIlI local _lIIlIllIII = Instance.new("UICorner") _lIIlIllIII.CornerRadius = UDim.new(0x0,0xC) _lIIlIllIII.Parent = _lIlIlIIIlI local owner = Instance.new("TextLabel") owner.Size = UDim2.new(0x1,0x0,0x0,0x23) owner.Position = UDim2.new(0x0,0x0,0x0,0x14) owner.Text = "Owner: ssxge" owner.TextScaled = true owner.BackgroundTransparency = 0x1 owner.Parent = _lIIIIIllIl _lIllIIllII(owner) local _lIIIIIIIll = Instance.new("TextLabel") _lIIIIIIIll.Size = UDim2.new(0x1,0x0,0x0,0x19) _lIIIIIIIll.Position = UDim2.new(0x0,0x0,0x0,0x3C) _lIIIIIIIll.Text = "Staff: Junior" _lIIIIIIIll.TextScaled = true _lIIIIIIIll.BackgroundTransparency = 0x1 _lIIIIIIIll.TextColor3 = Color3.fromRGB(0xAA,0x0,0xFF) _lIIIIIIIll.Parent = _lIIIIIllIl _lIllIIllII(_lIIIIIIIll) local _lllIIIlllI = Instance.new("TextLabel") _lllIIIlllI.Size = UDim2.new(0x1,0x0,0x0,0x19) _lllIIIlllI.Position = UDim2.new(0x0,0x0,0x0,0x5F) _lllIIIlllI.Text = "Press button to copy Discord invite" _lllIIIlllI.BackgroundTransparency = 0x1 _lllIIIlllI.TextColor3 = Color3.fromRGB(0xC8,0xC8,0xC8) _lllIIIlllI.Parent = _lIIIIIllIl _lllIIIlllI.TextScaled = true _lIllIIllII(_lllIIIlllI) local _lllIllIlIl = Instance.new("TextButton") _lllIllIlIl.Size = UDim2.new(0x0,0xDC,0x0,0x28) _lllIllIlIl.Position = UDim2.new(0.5,-0x6E,0x0,0x82) _lllIllIlIl.Text = " Copy Discord Invite" _lllIllIlIl.BackgroundColor3 = _llIlIIIIll _lllIllIlIl.TextColor3 = Color3.new(0x1,0x85,0x1) _lllIllIlIl.Parent = _lIIIIIllIl _lIllIIllII(_lllIllIlIl) local _lIIlIllllI = Instance.new("ImageLabel") _lIIlIllllI.Size = UDim2.new(0x0,0x18,0x0,0x18) _lIIlIllllI.Position = UDim2.new(0x0,0x8,0.5,-0xC) _lIIlIllllI.BackgroundTransparency = 0x1 _lIIlIllllI.Image = "rbxassetid://6031075938" _lIIlIllllI.Parent = _lllIllIlIl _lllIllIlIl.MouseButton1Click:Connect( function () if setclipboard then setclipboard(_lIllIIlIlI) end
 end
 ) local _lllIIIIIII = Instance.new("ScrollingFrame") _lllIIIIIII.Size = UDim2.new(0x1,0x0,0x1,0x0) _lllIIIIIII.Visible = false _lllIIIIIII.Active = true _lllIIIIIII.CanvasSize = UDim2.new(0x0,0x0,0x0,0x0) _lllIIIIIII.AutomaticCanvasSize = Enum.AutomaticSize.Y _lllIIIIIII.ScrollBarThickness = 0x6 _lllIIIIIII.BackgroundTransparency = 0x1 _lllIIIIIII.Parent = _lIIlIIllIl _lllIIIIIII.ScrollingEnabled = true _lllIIIIIII.ScrollBarImageTransparency = 0x0 local _llllIIllIl = Instance.new("ScrollingFrame") _llllIIllIl.Size = UDim2.new(0x1,0x0,0x1,0x0) _llllIIllIl.Visible = false _llllIIllIl.Active = true _llllIIllIl.CanvasSize = UDim2.new(0x0,0x0,0x0,0x0) _llllIIllIl.AutomaticCanvasSize = Enum.AutomaticSize.Y _llllIIllIl.ScrollBarThickness = 0x6 _llllIIllIl.BackgroundTransparency = 0x1 _llllIIllIl.Parent = _lIIlIIllIl _llllIIllIl.ScrollingEnabled = true _llllIIllIl.ScrollBarImageTransparency = 0x0 local _IllIIIllll = Instance.new("ScrollingFrame") _IllIIIllll.Size = UDim2.new(0x1,0x0,0x1,0x0) _IllIIIllll.Visible = false _IllIIIllll.Active = true _IllIIIllll.BackgroundTransparency = 0x1 _IllIIIllll.CanvasSize = UDim2.new(0x0,0x0,0x0,0x0) _IllIIIllll.AutomaticCanvasSize = Enum.AutomaticSize.Y _IllIIIllll.ScrollBarThickness = 0x6 _IllIIIllll.Parent = _lIIlIIllIl _IllIIIllll.ScrollingEnabled = true _IllIIIllll.ScrollBarImageTransparency = 0x0 local _lIlIlllIlI = Instance.new("ScrollingFrame") _lIlIlllIlI.Size = UDim2.new(0x1,0x0,0x1,0x0) _lIlIlllIlI.Visible = false _lIlIlllIlI.Active = true _lIlIlllIlI.CanvasSize = UDim2.new(0x0,0x0,0x0,0x0) _lIlIlllIlI.AutomaticCanvasSize = Enum.AutomaticSize.Y _lIlIlllIlI.ScrollBarThickness = 0x6 _lIlIlllIlI.BackgroundTransparency = 0x1 _lIlIlllIlI.Parent = _lIIlIIllIl _lIlIlllIlI.ScrollingEnabled = true _lIlIlllIlI.ScrollBarImageTransparency = 0x0 local _lllIlIIIlI = true local function _IIlIlllIII() _lllIlIIIlI = not _lllIlIIIlI if _lllIlIIIlI then _lIlIlIIIlI.Visible = true _lIlIlIIIlI.Size = UDim2.new(0x0,0x0,0x0,0x0) TweenService:Create(_lIlIlIIIlI, TweenInfo.new(0.35, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Size = UDim2.new(0x0,0x1B8,0x0,0x154)} ):Play() TweenService:Create(_lllllIIllI,TweenInfo.new(0.3),{Size = 0xE}):Play() else local _IIlIIIIIlI = TweenService:Create(_lIlIlIIIlI, TweenInfo.new(0.25, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {Size = UDim2.new(0x0,0x0,0x0,0x0)} ) _IIlIIIIIlI:Play() _IIlIIIIIlI.Completed:Wait() _lIlIlIIIlI.Visible = false TweenService:Create(_lllllIIllI,TweenInfo.new(0.3),{Size = 0x0}):Play() end
 end
 local _lIlIllIIIl = _IIlIIlllIl("Set Open/Close Keybind", 0x14, 0x14, _lIlIlllIlI) _lIlIllIIIl.MouseButton1Click:Connect( function () _lIlIllIIIl.Text = "Press any key..." _IIIlIlIIII = true end
 ) _llIlIIIlll.InputBegan:Connect( function (input, gp) if gp then return end
 if _IIIlIlIIII then _IIIlIlIIII = false _lIIIllIlll = input.KeyCode _lIlIllIIIl.Text = "Menu Key: " .. input.KeyCode.Name task.wait() return end
 if input.KeyCode == _lIIIllIlll then _IIlIlllIII() end
 if input.KeyCode == Enum.KeyCode.W then _IlIlIIIIlI.W = true end
 if input.KeyCode == Enum.KeyCode.A then _IlIlIIIIlI.A = true end
 if input.KeyCode == Enum.KeyCode.S then _IlIlIIIIlI.S = true end
 if input.KeyCode == Enum.KeyCode.D then _IlIlIIIIlI.D = true end
 if input.KeyCode == Enum.KeyCode.Space then _IlIlIIIIlI.Space = true end
 if input.KeyCode == Enum.KeyCode.LeftControl then _IlIlIIIIlI.Ctrl = true end
 end
 ) local _llIIlIlIII = false local _IIllIIlIII = nil local _llllIllIlI = Instance.new("TextBox") _llllIllIlI.Size = UDim2.new(0x0,0xDC,0x0,0x23) _llllIllIlI.Position = UDim2.new(0.5,-0x6E,0x0,0x14) _llllIllIlI.PlaceholderText = "Enter username or 'all'" _llllIllIlI.Text = "" _llllIllIlI.TextScaled = true _llllIllIlI.BackgroundColor3 = _lIlIIIIIlI _llllIllIlI.TextColor3 = Color3.new(0x1,0x1,0x1) _llllIllIlI.Parent = _IllIIIllll _lIllIIllII(_llllIllIlI) local _lllIlIllII = _IIlIIlllIl("Fling Player",0x14,0x46,_IllIIIllll) local _IIIlIllIlI = _IIlIIlllIl("Teleport To Player",0xF0,0x46,_IllIIIllll) local _llIIIIlIII = _IIlIIlllIl("View Player",0x14,0x78,_IllIIIllll) local _IIIIllIIlI = { Main = _lIIIIIllIl, Player = _lllIIIIIII, View = _llllIIllIl, Server = _IllIIIllll, Settings = _lIlIlllIlI } local function _IIlIIlIIII(tabName) for name, frame in pairs(_IIIIllIIlI) do frame.Visible = (name == tabName) end
 end
 _IIlllIIIlI.MouseButton1Click:Connect( function () print("Switching to Main Tab") _IIlIIlIIII("Main") end
 ) _IIIIIlIlIl.MouseButton1Click:Connect( function () print("Switching to Player Tab") _IIlIIlIIII("Player") end
 ) _llIlIlIlll.MouseButton1Click:Connect( function () print("Switching to View Tab") _IIlIIlIIII("View") end
 ) _lllIIIlIIl.MouseButton1Click:Connect( function () print("Switching to Server Tab") _IIlIIlIIII("Server") end
 ) _lIIIllIIIl.MouseButton1Click:Connect( function () print("Switching to Settings Tab") _IIlIIlIIII("Settings") end
 ) task.wait() _IIlIIlIIII("Main") local _IIIIIIllII = 0x14 local _lIllllIIlI = 0xF0 local _IIlIlIIIll = 0x14 local _lIlllIIIII = _IIlIIlllIl("Fly",_IIIIIIllII,_IIlIlIIIll,_lllIIIIIII) local _lIllIIlIIl = _IIlIIlllIl("Noclip",_lIllllIIlI,_IIlIlIIIll,_lllIIIIIII) _IIlIlIIIll = _IIlIlIIIll + 0x28 local _IIIlIIIlIl = Instance.new("TextLabel") _IIIlIIIlIl.Size = UDim2.new(0x0,0xB4,0x0,0x19) _IIIlIIIlIl.Position = UDim2.new(0x0,_IIIIIIllII,0x0,_IIlIlIIIll) _IIIlIIIlIl.Text = "Fly Speed: "..flySpeed _IIIlIIIlIl.BackgroundTransparency = 0x1 _IIIlIIIlIl.TextColor3 = Color3.new(0x1,0x1,0x1) _IIIlIIIlIl.Parent = _lllIIIIIII _lIllIIllII(_IIIlIIIlIl) local _llllIlIlll = _IIlIIlllIl("-",_IIIIIIllII,_IIlIlIIIll+0x19,_lllIIIIIII) _llllIlIlll.Size = UDim2.new(0x0,0x50,0x0,0x1E) local _IllllIllll = _IIlIIlllIl("+",_IIIIIIllII+0x5A,_IIlIlIIIll+0x19,_lllIIIIIII) _IllllIllll.Size = UDim2.new(0x0,0x50,0x0,0x1E) local function _lIlIlllllI(name) name = name:lower() for _,plr in pairs(Players:GetPlayers()) do if plr.Name:lower():sub(0x1,#name) == name then return plr end
 end
 end
 local function _llIlIIIIIl(_llIIIIIIII) if not _llIIIIIIII.Character then return end
 if not _IIIIIlIIlI.Character then return end
 local _IIIlIIlllI = _IIIIIlIIlI.Character:FindFirstChild("HumanoidRootPart") local _llIIIllIlI = _llIIIIIIII.Character:FindFirstChild("HumanoidRootPart") if not _IIIlIIlllI or not _llIIIllIlI then return end
 local _lIllIlIIlI = _IIIlIIlllI.CFrame local _lllIllllII = Instance.new("BodyVelocity") _lllIllllII.MaxForce = Vector3.new(1e10,1e10,1e10) _lllIllllII.Parent = _IIIlIIlllI local _IIIlIIllll = Instance.new("BodyGyro") _IIIlIIllll.MaxTorque = Vector3.new(9e9,9e9,9e9) _IIIlIIllll.P = 9e4 _IIIlIIllll.Parent = _IIIlIIlllI for i = 0x1,0x8C do if not _llIIIIIIII.Character then break end
 _llIIIllIlI = _llIIIIIIII.Character:FindFirstChild("HumanoidRootPart") if not _llIIIllIlI then break end
 _IIIlIIlllI.CFrame = _llIIIllIlI.CFrame _IIIlIIlllI.AssemblyAngularVelocity = Vector3.new( math.random(-0x1388,0x1388), math.random(-0x1388,0x1388), math.random(-0x1388,0x1388) ) _lllIllllII.Velocity = Vector3.new( math.random(-0x9C4,0x9C4), math.random(0x320,0x640), math.random(-0x9C4,0x9C4) ) RunService.Heartbeat:Wait() end
 _lllIllllII:Destroy() _IIIlIIllll:Destroy() _IIIlIIlllI.AssemblyLinearVelocity = Vector3.zero _IIIlIIlllI.AssemblyAngularVelocity = Vector3.zero task.wait() _IIIlIIlllI.CFrame = _lIllIlIIlI end
 local function _lllIllIIlI(_llIIIIIIII) if not _llIIIIIIII.Character then return end
 if not _IIIIIlIIlI.Character then return end
 local _IIIlIIlllI = _IIIIIlIIlI.Character:FindFirstChild("HumanoidRootPart") local _llIIIllIlI = _llIIIIIIII.Character:FindFirstChild("HumanoidRootPart") if not _IIIlIIlllI or not _llIIIllIlI then return end
 _IIIlIIlllI.CFrame = _llIIIllIlI.CFrame * CFrame.new(0x0,0x0,-0x3) end
 _lllIlIllII.MouseButton1Click:Connect( function () local _llllllllII = _llllIllIlI.Text if _llllllllII == "" then return end
 if _llllllllII:lower() == "all" then for _,plr in pairs(Players:GetPlayers()) do if plr ~= _IIIIIlIIlI then _llIlIIIIIl(plr) task.wait(0.3) end
 end
 else local _llIIIIIIII = _lIlIlllllI(_llllllllII) if _llIIIIIIII and _llIIIIIIII ~= _IIIIIlIIlI then _llIlIIIIIl(_llIIIIIIII) end
 end
 end
 ) _IIIlIllIlI.MouseButton1Click:Connect( function () local _llllllllII = _llllIllIlI.Text if _llllllllII == "" then return end
 if _llllllllII:lower() == "all" then for _,plr in pairs(Players:GetPlayers()) do if plr ~= _IIIIIlIIlI then _lllIllIIlI(plr) task.wait(0.4) end
 end
 else local _llIIIIIIII = _lIlIlllllI(_llllllllII) if _llIIIIIIII and _llIIIIIIII ~= _IIIIIlIIlI then _lllIllIIlI(_llIIIIIIII) end
 end
 end
 ) local _lllIIlIIIl = workspace.CurrentCamera _llIIIIlIII.MouseButton1Click:Connect( function () if _llIIlIlIII then if _IIIIIlIIlI.Character and _IIIIIlIIlI.Character:FindFirstChild("Humanoid") then _lllIIlIIIl.CameraSubject = _IIIIIlIIlI.Character.Humanoid end
 _llIIlIlIII = false _IIllIIlIII = nil _llIIIIlIII.Text = "View Player" return end
 local _llllllllII = _llllIllIlI.Text if _llllllllII == "" then return end
 local _llIIIIIIII = _lIlIlllllI(_llllllllII) if _llIIIIIIII and _llIIIIIIII.Character then local _llIIllIIIl = _llIIIIIIII.Character:FindFirstChildOfClass("Humanoid") if _llIIllIIIl then _lllIIlIIIl.CameraSubject = _llIIllIIIl _llIIlIlIII = true _IIllIIlIII = _llIIIIIIII _llIIIIlIII.Text = "Stop Viewing" end
 end
 end
 ) local _lIlIlllllI = Instance.new("TextLabel") _lIlIlllllI.Size = UDim2.new(0x0,0xB4,0x0,0x19) _lIlIlllllI.Position = UDim2.new(0x0,_lIllllIIlI,0x0,_IIlIlIIIll) _lIlIlllllI.Text = "WalkSpeed: "..walkSpeed _lIlIlllllI.BackgroundTransparency = 0x1 _lIlIlllllI.TextColor3 = Color3.new(0x1,0x1,0x1) _lIlIlllllI.Parent = _lllIIIIIII _lIllIIllII(_lIlIlllllI) local _IlllIlIIIl = _IIlIIlllIl("-",_lIllllIIlI,_IIlIlIIIll+0x19,_lllIIIIIII) _IlllIlIIIl.Size = UDim2.new(0x0,0x50,0x0,0x1E) local _IllllllIIl = _IIlIIlllIl("+",_lIllllIIlI+0x5A,_IIlIlIIIll+0x19,_lllIIIIIII) _IllllllIIl.Size = UDim2.new(0x0,0x50,0x0,0x1E) _IllllIllll.MouseButton1Click:Connect( function () _IllllIllII += 0x14 _IIIlIIIlIl.Text = "Fly Speed: "..flySpeed end
 ) _llllIlIlll.MouseButton1Click:Connect( function () _IllllIllII = math.max(0xA,_IllllIllII-0x14) _IIIlIIIlIl.Text = "Fly Speed: "..flySpeed end
 ) _IllllllIIl.MouseButton1Click:Connect( function () _lIlIIllllI += 0x5 _lIlIlllllI.Text = "WalkSpeed: "..walkSpeed local _lIIlIIIlII = _IIIIIlIIlI.Character and _IIIIIlIIlI.Character:FindFirstChildOfClass("Humanoid") if _lIIlIIIlII then _lIIlIIIlII.WalkSpeed = _lIlIIllllI end
 end
 ) _IlllIlIIIl.MouseButton1Click:Connect( function () _lIlIIllllI = math.max(0x5,_lIlIIllllI-0x5) _lIlIlllllI.Text = "WalkSpeed: "..walkSpeed local _lIIlIIIlII = _IIIIIlIIlI.Character and _IIIIIlIIlI.Character:FindFirstChildOfClass("Humanoid") if _lIIlIIIlII then _lIIlIIIlII.WalkSpeed = _lIlIIllllI end
 end
 ) RunService.RenderStepped:Connect( function () local _IIIIIIllll = (tick() % 0x5) / 0x5 local _IIIlIIllII = Color3.fromHSV(_IIIIIIllll,0x1,0x1) if owner then owner.TextColor3 = _IIIlIIllII end
 if _llIlllllIl then for _,esp in pairs(_lIlIlIlllI) do if esp then esp.OutlineColor = _IIIlIIllII end
 end
 end
 end
 ) local _lIlIlIlllI = {} local function _IlIIIlIllI(plr) if plr == _IIIIIlIIlI then return end
 local function _IlIlIIlIIl(_IlllIlIlIl) if _lIlIlIlllI[plr] then _lIlIlIlllI[plr]:Destroy() end
 local _lIIlIIIlII = Instance.new("Highlight") _lIIlIIIlII.FillTransparency = 0x1 _lIIlIIIlII.OutlineTransparency = 0x0 _lIIlIIIlII.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop _lIIlIIIlII.Adornee = _IlllIlIlIl local _IIIIIIllll = (tick() % 0x5) / 0x5 _lIIlIIIlII.OutlineColor = Color3.fromHSV(_IIIIIIllll,0x1,0x1) _lIIlIIIlII.Parent = _IlllIlIlIl _lIlIlIlllI[plr] = _lIIlIIIlII end
 if plr.Character then _IlIlIIlIIl(plr.Character) end
 plr.CharacterAdded:Connect(_IlIlIIlIIl) end
 local function _IllIIlllll() for _,plr in pairs(Players:GetPlayers()) do if plr.Character then for _,v in pairs(plr.Character:GetChildren()) do if v:IsA("Highlight") then v:Destroy() end
 end
 end
 end
 _lIlIlIlllI = {} end
 local _lllllIlIII = _IIlIIlllIl("Toggle ESP",0x78,0x28,_llllIIllIl) _lllllIlIII.MouseButton1Click:Connect( function () _llIlllllIl = not _llIlllllIl if _llIlllllIl then for _,plr in pairs(Players:GetPlayers()) do _IlIIIlIllI(plr) end
 _lllllIlIII.Text = "ESP: ON" else _IllIIlllll() _lllllIlIII.Text = "Toggle ESP" end
 end
 ) RunService.RenderStepped:Connect( function () local _IIIIIIllll = (tick() % 0x5) / 0x5 local _IIIlIIllII = Color3.fromHSV(_IIIIIIllll,0x1,0x1) if owner then owner.TextColor3 = _IIIlIIllII end
 if _llIlllllIl then for _,highlight in pairs(_lIlIlIlllI) do if highlight then highlight.OutlineColor = _IIIlIIllII end
 end
 end
 end
 ) _IIIIIlIIlI.CharacterAdded:Connect( function (_IlllIlIlIl) local _llIIllIIIl = _IlllIlIlIl:WaitForChild("Humanoid") _llIIllIIIl.WalkSpeed = _lIlIIllllI end
 ) RunService.Stepped:Connect( function () if _llIlIlIllI and _IIIIIlIIlI.Character then for _,part in pairs(_IIIIIlIIlI.Character:GetDescendants()) do if part:IsA("BasePart") then part.CanCollide = false end
 end
 end
 end
 ) _lIllIIlIIl.MouseButton1Click:Connect( function () _llIlIlIllI = not _llIlIlIllI if _llIlIlIllI then _lIllIIlIIl.Text = "Noclip: ON" else _lIllIIlIIl.Text = "Noclip" end
 end
 ) local function _lIIllllIll() local _IlllIlIlIl = _IIIIIlIIlI.Character if not _IlllIlIlIl then return end
 local _IIIIlIlIIl = _IlllIlIlIl:FindFirstChild("HumanoidRootPart") if not _IIIIlIlIIl then return end
 _IlIlIlIIll = Instance.new("BodyVelocity") _IlIlIlIIll.MaxForce = Vector3.new(9e9,9e9,9e9) _IlIlIlIIll.Velocity = Vector3.zero _IlIlIlIIll.Parent = _IIIIlIlIIl _lIIIlIllll = Instance.new("BodyGyro") _lIIIlIllll.MaxTorque = Vector3.new(9e9,9e9,9e9) _lIIIlIllll.CFrame = _IIIIlIlIIl.CFrame _lIIIlIllll.Parent = _IIIIlIlIIl _llIllllIIl = true end
 local function _llIIIlIIII() _llIllllIIl = false if _IlIlIlIIll then _IlIlIlIIll:Destroy() _IlIlIlIIll = nil end
 if _lIIIlIllll then _lIIIlIllll:Destroy() _lIIIlIllll = nil end
 end
 _lIlllIIIII.MouseButton1Click:Connect( function () if _llIllllIIl then _llIIIlIIII() _lIlllIIIII.Text = "Fly" else _lIIllllIll() _lIlllIIIII.Text = "Fly: ON" end
 end
 ) _llIlIIIlll.InputEnded:Connect( function (input) if input.KeyCode == Enum.KeyCode.W then _IlIlIIIIlI.W = false end
 if input.KeyCode == Enum.KeyCode.A then _IlIlIIIIlI.A = false end
 if input.KeyCode == Enum.KeyCode.S then _IlIlIIIIlI.S = false end
 if input.KeyCode == Enum.KeyCode.D then _IlIlIIIIlI.D = false end
 if input.KeyCode == Enum.KeyCode.Space then _IlIlIIIIlI.Space = false end
 if input.KeyCode == Enum.KeyCode.LeftControl then _IlIlIIIIlI.Ctrl = false end
 end
 ) RunService.RenderStepped:Connect( function () if _llIllllIIl and _IIIIIlIIlI.Character then local _IIIIlIlIIl = _IIIIIlIIlI.Character:FindFirstChild("HumanoidRootPart") if not _IIIIlIlIIl then return end
 local _IIIlIllIll = workspace.CurrentCamera if _lIIIlIllll then _lIIIlIllll.CFrame = _IIIlIllIll.CFrame end
 local _IIllIlIlII = Vector3.zero if _IlIlIIIIlI.W then _IIllIlIlII += _IIIlIllIll.CFrame.LookVector end
 if _IlIlIIIIlI.S then _IIllIlIlII -= _IIIlIllIll.CFrame.LookVector end
 if _IlIlIIIIlI.A then _IIllIlIlII -= _IIIlIllIll.CFrame.RightVector end
 if _IlIlIIIIlI.D then _IIllIlIlII += _IIIlIllIll.CFrame.RightVector end
 if _IlIlIIIIlI.Space then _IIllIlIlII += _IIIlIllIll.CFrame.UpVector end
 if _IlIlIIIIlI.Ctrl then _IIllIlIlII -= _IIIlIllIll.CFrame.UpVector end
 if _IlIlIlIIll then _IlIlIlIIll.Velocity = _IIllIlIlII * _IllllIllII end
 end
 end
 )
